version: "3.11"

services:
  pgdb:
    container_name: pgdb_ecommerce
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #esearch:
  #  container_name: search
  #  image: elasticsearch:8.8.1
  #  environment: 
  #    - xpack.security.enabled=false
  #   - discovery.type=single-node
  #  ports:      
  #    - "9200:9200"